export const tracks: SpotifyApi.PlaylistTrackResponse = {
  href: 'https://api.spotify.com/v1/playlists/7M9SBTpzYTGtnWSr1ssOJx/tracks?offset=0&limit=100&locale=en-US,en;q%3D0.5',
  items: [
    {
      added_at: '2025-01-18T16:52:00Z',
      added_by: {
        external_urls: { spotify: 'https://open.spotify.com/user/alxtrimpe' },
        href: 'https://api.spotify.com/v1/users/alxtrimpe',
        id: 'alxtrimpe',
        type: 'user',
        uri: 'spotify:user:alxtrimpe',
      },
      is_local: false,
      primary_color: null,
      track: {
        preview_url: null,
        available_markets: ['AR', 'AU', 'AT', 'BE', 'BO'],
        explicit: true,
        type: 'track',
        episode: false,
        track: true,
        album: {
          available_markets: ['AR', 'AU', 'AT', 'BE', 'BO'],
          type: 'album',
          album_type: 'album',
          href: 'https://api.spotify.com/v1/albums/1lg41BuPdVJMsDwLZiVDF6',
          id: '1lg41BuPdVJMsDwLZiVDF6',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273c4e2c0dacbae3e342ac21944',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02c4e2c0dacbae3e342ac21944',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851c4e2c0dacbae3e342ac21944',
              width: 64,
            },
          ],
          name: 'Believers',
          release_date: '2013-07-16',
          release_date_precision: 'day',
          uri: 'spotify:album:1lg41BuPdVJMsDwLZiVDF6',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/71WhWdsVNTLxsnfe8M3Peh',
              },
              href: 'https://api.spotify.com/v1/artists/71WhWdsVNTLxsnfe8M3Peh',
              id: '71WhWdsVNTLxsnfe8M3Peh',
              name: '¡MAYDAY!',
              type: 'artist',
              uri: 'spotify:artist:71WhWdsVNTLxsnfe8M3Peh',
            },
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/1lg41BuPdVJMsDwLZiVDF6',
          },
          total_tracks: 15,
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/71WhWdsVNTLxsnfe8M3Peh',
            },
            href: 'https://api.spotify.com/v1/artists/71WhWdsVNTLxsnfe8M3Peh',
            id: '71WhWdsVNTLxsnfe8M3Peh',
            name: '¡MAYDAY!',
            type: 'artist',
            uri: 'spotify:artist:71WhWdsVNTLxsnfe8M3Peh',
          },
        ],
        disc_number: 1,
        track_number: 1,
        duration_ms: 185880,
        external_ids: { isrc: 'USQY51398810' },
        external_urls: {
          spotify: 'https://open.spotify.com/track/28MRSuy6PBcR42LbNldzj0',
        },
        href: 'https://api.spotify.com/v1/tracks/28MRSuy6PBcR42LbNldzj0',
        id: '28MRSuy6PBcR42LbNldzj0',
        name: 'Believers',
        popularity: 35,
        uri: 'spotify:track:28MRSuy6PBcR42LbNldzj0',
        is_local: false,
      },
      video_thumbnail: { url: null },
    },
    {
      added_at: '2025-01-18T16:52:02Z',
      added_by: {
        external_urls: { spotify: 'https://open.spotify.com/user/alxtrimpe' },
        href: 'https://api.spotify.com/v1/users/alxtrimpe',
        id: 'alxtrimpe',
        type: 'user',
        uri: 'spotify:user:alxtrimpe',
      },
      is_local: false,
      primary_color: null,
      track: {
        preview_url: null,
        available_markets: ['AR', 'AU', 'AT', 'BE', 'BO'],
        explicit: true,
        type: 'track',
        episode: false,
        track: true,
        album: {
          available_markets: ['AR', 'AU', 'AT', 'BE', 'BO'],
          type: 'album',
          album_type: 'album',
          href: 'https://api.spotify.com/v1/albums/7rWNM4Q11nvmpHOuSnLFME',
          id: '7rWNM4Q11nvmpHOuSnLFME',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b2730e39c79a29ace0bf642b8415',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e020e39c79a29ace0bf642b8415',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d000048510e39c79a29ace0bf642b8415',
              width: 64,
            },
          ],
          name: 'Revolver (Expanded Edition)',
          release_date: '2011-12-06',
          release_date_precision: 'day',
          uri: 'spotify:album:7rWNM4Q11nvmpHOuSnLFME',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/3aQeKQSyrW4qWr35idm0cy',
              },
              href: 'https://api.spotify.com/v1/artists/3aQeKQSyrW4qWr35idm0cy',
              id: '3aQeKQSyrW4qWr35idm0cy',
              name: 'T-Pain',
              type: 'artist',
              uri: 'spotify:artist:3aQeKQSyrW4qWr35idm0cy',
            },
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/7rWNM4Q11nvmpHOuSnLFME',
          },
          total_tracks: 20,
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3aQeKQSyrW4qWr35idm0cy',
            },
            href: 'https://api.spotify.com/v1/artists/3aQeKQSyrW4qWr35idm0cy',
            id: '3aQeKQSyrW4qWr35idm0cy',
            name: 'T-Pain',
            type: 'artist',
            uri: 'spotify:artist:3aQeKQSyrW4qWr35idm0cy',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/13saZpZnCDWOI9D4IJhp1f',
            },
            href: 'https://api.spotify.com/v1/artists/13saZpZnCDWOI9D4IJhp1f',
            id: '13saZpZnCDWOI9D4IJhp1f',
            name: 'Lily Allen',
            type: 'artist',
            uri: 'spotify:artist:13saZpZnCDWOI9D4IJhp1f',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/137W8MRPWKqSmrBGDBFSop',
            },
            href: 'https://api.spotify.com/v1/artists/137W8MRPWKqSmrBGDBFSop',
            id: '137W8MRPWKqSmrBGDBFSop',
            name: 'Wiz Khalifa',
            type: 'artist',
            uri: 'spotify:artist:137W8MRPWKqSmrBGDBFSop',
          },
        ],
        disc_number: 1,
        track_number: 5,
        duration_ms: 281280,
        external_ids: { isrc: 'USJI11100299' },
        external_urls: {
          spotify: 'https://open.spotify.com/track/42EMFjvFtOki8MA0JNZqVK',
        },
        href: 'https://api.spotify.com/v1/tracks/42EMFjvFtOki8MA0JNZqVK',
        id: '42EMFjvFtOki8MA0JNZqVK',
        name: "5 O'Clock (feat. Lily Allen & Wiz Khalifa)",
        popularity: 55,
        uri: 'spotify:track:42EMFjvFtOki8MA0JNZqVK',
        is_local: false,
      },
      video_thumbnail: { url: null },
    },
    {
      added_at: '2025-01-18T16:52:04Z',
      added_by: {
        external_urls: { spotify: 'https://open.spotify.com/user/alxtrimpe' },
        href: 'https://api.spotify.com/v1/users/alxtrimpe',
        id: 'alxtrimpe',
        type: 'user',
        uri: 'spotify:user:alxtrimpe',
      },
      is_local: false,
      primary_color: null,
      track: {
        preview_url: null,
        available_markets: ['AR', 'AU', 'AT'],
        explicit: false,
        type: 'track',
        episode: false,
        track: true,
        album: {
          available_markets: ['AR', 'AU', 'AT', 'BE', 'BO', 'BR'],
          type: 'album',
          album_type: 'album',
          href: 'https://api.spotify.com/v1/albums/0K88Nzh4Zd6ywceshg1A3B',
          id: '0K88Nzh4Zd6ywceshg1A3B',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273f3a3655a30454f65e259814c',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02f3a3655a30454f65e259814c',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851f3a3655a30454f65e259814c',
              width: 64,
            },
          ],
          name: 'Goddess (Remixes)',
          release_date: '2015-03-23',
          release_date_precision: 'day',
          uri: 'spotify:album:0K88Nzh4Zd6ywceshg1A3B',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/2xe8IXgCTpwHE3eA9hTs4n',
              },
              href: 'https://api.spotify.com/v1/artists/2xe8IXgCTpwHE3eA9hTs4n',
              id: '2xe8IXgCTpwHE3eA9hTs4n',
              name: 'BANKS',
              type: 'artist',
              uri: 'spotify:artist:2xe8IXgCTpwHE3eA9hTs4n',
            },
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/0K88Nzh4Zd6ywceshg1A3B',
          },
          total_tracks: 18,
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2xe8IXgCTpwHE3eA9hTs4n',
            },
            href: 'https://api.spotify.com/v1/artists/2xe8IXgCTpwHE3eA9hTs4n',
            id: '2xe8IXgCTpwHE3eA9hTs4n',
            name: 'BANKS',
            type: 'artist',
            uri: 'spotify:artist:2xe8IXgCTpwHE3eA9hTs4n',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7Gn0urVHbuAuUcv5SP6bKn',
            },
            href: 'https://api.spotify.com/v1/artists/7Gn0urVHbuAuUcv5SP6bKn',
            id: '7Gn0urVHbuAuUcv5SP6bKn',
            name: 'Andrew Swanson',
            type: 'artist',
            uri: 'spotify:artist:7Gn0urVHbuAuUcv5SP6bKn',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/24GBmL4OVczm31u0MmDLDf',
            },
            href: 'https://api.spotify.com/v1/artists/24GBmL4OVczm31u0MmDLDf',
            id: '24GBmL4OVczm31u0MmDLDf',
            name: 'Henry Allen',
            type: 'artist',
            uri: 'spotify:artist:24GBmL4OVczm31u0MmDLDf',
          },
        ],
        disc_number: 1,
        track_number: 4,
        duration_ms: 252504,
        external_ids: { isrc: 'USUM71500177' },
        external_urls: {
          spotify: 'https://open.spotify.com/track/4ckVs2KqZix1xuM3ZQtNb2',
        },
        href: 'https://api.spotify.com/v1/tracks/4ckVs2KqZix1xuM3ZQtNb2',
        id: '4ckVs2KqZix1xuM3ZQtNb2',
        name: 'Beggin For Thread - BTS Remix',
        popularity: 20,
        uri: 'spotify:track:4ckVs2KqZix1xuM3ZQtNb2',
        is_local: false,
      },
      video_thumbnail: { url: null },
    },
  ],
  limit: 100,
  next: 'https://api.spotify.com/v1/playlists/7M9SBTpzYTGtnWSr1ssOJx/tracks?offset=100&limit=100&locale=en-US,en;q%3D0.5',
  offset: 0,
  previous: null,
  total: 3549,
} as any;
