export const tracks: SpotifyApi.PlaylistTrackResponse = {
  href: 'https://api.spotify.com/v1/playlists/7M9SBTpzYTGtnWSr1ssOJx/tracks?offset=0&limit=100&locale=en-US,en;q%3D0.5',
  items: [
    {
      added_at: '2025-01-18T16:52:00Z',
      added_by: {
        external_urls: { spotify: 'https://open.spotify.com/user/alxtrimpe' },
        href: 'https://api.spotify.com/v1/users/alxtrimpe',
        id: 'alxtrimpe',
        type: 'user',
        uri: 'spotify:user:alxtrimpe',
      },
      is_local: false,
      primary_color: null,
      track: {
        preview_url: null,
        available_markets: ['AR', 'AU', 'AT', 'BE', 'BO'],
        explicit: true,
        type: 'track',
        episode: false,
        track: true,
        album: {
          available_markets: ['AR', 'AU', 'AT', 'BE', 'BO'],
          type: 'album',
          album_type: 'album',
          href: 'https://api.spotify.com/v1/albums/1lg41BuPdVJMsDwLZiVDF6',
          id: '1lg41BuPdVJMsDwLZiVDF6',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273c4e2c0dacbae3e342ac21944',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02c4e2c0dacbae3e342ac21944',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851c4e2c0dacbae3e342ac21944',
              width: 64,
            },
          ],
          name: 'Believers',
          release_date: '2013-07-16',
          release_date_precision: 'day',
          uri: 'spotify:album:1lg41BuPdVJMsDwLZiVDF6',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/71WhWdsVNTLxsnfe8M3Peh',
              },
              href: 'https://api.spotify.com/v1/artists/71WhWdsVNTLxsnfe8M3Peh',
              id: '71WhWdsVNTLxsnfe8M3Peh',
              name: '¡MAYDAY!',
              type: 'artist',
              uri: 'spotify:artist:71WhWdsVNTLxsnfe8M3Peh',
            },
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/1lg41BuPdVJMsDwLZiVDF6',
          },
          total_tracks: 15,
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/71WhWdsVNTLxsnfe8M3Peh',
            },
            href: 'https://api.spotify.com/v1/artists/71WhWdsVNTLxsnfe8M3Peh',
            id: '71WhWdsVNTLxsnfe8M3Peh',
            name: '¡MAYDAY!',
            type: 'artist',
            uri: 'spotify:artist:71WhWdsVNTLxsnfe8M3Peh',
          },
        ],
        disc_number: 1,
        track_number: 1,
        duration_ms: 185880,
        external_ids: { isrc: 'USQY51398810' },
        external_urls: {
          spotify: 'https://open.spotify.com/track/28MRSuy6PBcR42LbNldzj0',
        },
        href: 'https://api.spotify.com/v1/tracks/28MRSuy6PBcR42LbNldzj0',
        id: '28MRSuy6PBcR42LbNldzj0',
        name: 'Believers',
        popularity: 35,
        uri: 'spotify:track:28MRSuy6PBcR42LbNldzj0',
        is_local: false,
      },
      video_thumbnail: { url: null },
    },
    {
      added_at: '2025-01-18T16:52:02Z',
      added_by: {
        external_urls: { spotify: 'https://open.spotify.com/user/alxtrimpe' },
        href: 'https://api.spotify.com/v1/users/alxtrimpe',
        id: 'alxtrimpe',
        type: 'user',
        uri: 'spotify:user:alxtrimpe',
      },
      is_local: false,
      primary_color: null,
      track: {
        preview_url: null,
        available_markets: ['AR', 'AU', 'AT', 'BE', 'BO'],
        explicit: true,
        type: 'track',
        episode: false,
        track: true,
        album: {
          available_markets: ['AR', 'AU', 'AT', 'BE', 'BO'],
          type: 'album',
          album_type: 'album',
          href: 'https://api.spotify.com/v1/albums/7rWNM4Q11nvmpHOuSnLFME',
          id: '7rWNM4Q11nvmpHOuSnLFME',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b2730e39c79a29ace0bf642b8415',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e020e39c79a29ace0bf642b8415',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d000048510e39c79a29ace0bf642b8415',
              width: 64,
            },
          ],
          name: 'Revolver (Expanded Edition)',
          release_date: '2011-12-06',
          release_date_precision: 'day',
          uri: 'spotify:album:7rWNM4Q11nvmpHOuSnLFME',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/3aQeKQSyrW4qWr35idm0cy',
              },
              href: 'https://api.spotify.com/v1/artists/3aQeKQSyrW4qWr35idm0cy',
              id: '3aQeKQSyrW4qWr35idm0cy',
              name: 'T-Pain',
              type: 'artist',
              uri: 'spotify:artist:3aQeKQSyrW4qWr35idm0cy',
            },
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/7rWNM4Q11nvmpHOuSnLFME',
          },
          total_tracks: 20,
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3aQeKQSyrW4qWr35idm0cy',
            },
            href: 'https://api.spotify.com/v1/artists/3aQeKQSyrW4qWr35idm0cy',
            id: '3aQeKQSyrW4qWr35idm0cy',
            name: 'T-Pain',
            type: 'artist',
            uri: 'spotify:artist:3aQeKQSyrW4qWr35idm0cy',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/13saZpZnCDWOI9D4IJhp1f',
            },
            href: 'https://api.spotify.com/v1/artists/13saZpZnCDWOI9D4IJhp1f',
            id: '13saZpZnCDWOI9D4IJhp1f',
            name: 'Lily Allen',
            type: 'artist',
            uri: 'spotify:artist:13saZpZnCDWOI9D4IJhp1f',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/137W8MRPWKqSmrBGDBFSop',
            },
            href: 'https://api.spotify.com/v1/artists/137W8MRPWKqSmrBGDBFSop',
            id: '137W8MRPWKqSmrBGDBFSop',
            name: 'Wiz Khalifa',
            type: 'artist',
            uri: 'spotify:artist:137W8MRPWKqSmrBGDBFSop',
          },
        ],
        disc_number: 1,
        track_number: 5,
        duration_ms: 281280,
        external_ids: { isrc: 'USJI11100299' },
        external_urls: {
          spotify: 'https://open.spotify.com/track/42EMFjvFtOki8MA0JNZqVK',
        },
        href: 'https://api.spotify.com/v1/tracks/42EMFjvFtOki8MA0JNZqVK',
        id: '42EMFjvFtOki8MA0JNZqVK',
        name: "5 O'Clock (feat. Lily Allen & Wiz Khalifa)",
        popularity: 55,
        uri: 'spotify:track:42EMFjvFtOki8MA0JNZqVK',
        is_local: false,
      },
      video_thumbnail: { url: null },
    },
    {
      added_at: '2025-01-18T16:52:04Z',
      added_by: {
        external_urls: { spotify: 'https://open.spotify.com/user/alxtrimpe' },
        href: 'https://api.spotify.com/v1/users/alxtrimpe',
        id: 'alxtrimpe',
        type: 'user',
        uri: 'spotify:user:alxtrimpe',
      },
      is_local: false,
      primary_color: null,
      track: {
        preview_url: null,
        available_markets: ['AR', 'AU', 'AT'],
        explicit: false,
        type: 'track',
        episode: false,
        track: true,
        album: {
          available_markets: ['AR', 'AU', 'AT', 'BE', 'BO', 'BR'],
          type: 'album',
          album_type: 'album',
          href: 'https://api.spotify.com/v1/albums/0K88Nzh4Zd6ywceshg1A3B',
          id: '0K88Nzh4Zd6ywceshg1A3B',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273f3a3655a30454f65e259814c',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02f3a3655a30454f65e259814c',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851f3a3655a30454f65e259814c',
              width: 64,
            },
          ],
          name: 'Goddess (Remixes)',
          release_date: '2015-03-23',
          release_date_precision: 'day',
          uri: 'spotify:album:0K88Nzh4Zd6ywceshg1A3B',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/2xe8IXgCTpwHE3eA9hTs4n',
              },
              href: 'https://api.spotify.com/v1/artists/2xe8IXgCTpwHE3eA9hTs4n',
              id: '2xe8IXgCTpwHE3eA9hTs4n',
              name: 'BANKS',
              type: 'artist',
              uri: 'spotify:artist:2xe8IXgCTpwHE3eA9hTs4n',
            },
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/0K88Nzh4Zd6ywceshg1A3B',
          },
          total_tracks: 18,
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2xe8IXgCTpwHE3eA9hTs4n',
            },
            href: 'https://api.spotify.com/v1/artists/2xe8IXgCTpwHE3eA9hTs4n',
            id: '2xe8IXgCTpwHE3eA9hTs4n',
            name: 'BANKS',
            type: 'artist',
            uri: 'spotify:artist:2xe8IXgCTpwHE3eA9hTs4n',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7Gn0urVHbuAuUcv5SP6bKn',
            },
            href: 'https://api.spotify.com/v1/artists/7Gn0urVHbuAuUcv5SP6bKn',
            id: '7Gn0urVHbuAuUcv5SP6bKn',
            name: 'Andrew Swanson',
            type: 'artist',
            uri: 'spotify:artist:7Gn0urVHbuAuUcv5SP6bKn',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/24GBmL4OVczm31u0MmDLDf',
            },
            href: 'https://api.spotify.com/v1/artists/24GBmL4OVczm31u0MmDLDf',
            id: '24GBmL4OVczm31u0MmDLDf',
            name: 'Henry Allen',
            type: 'artist',
            uri: 'spotify:artist:24GBmL4OVczm31u0MmDLDf',
          },
        ],
        disc_number: 1,
        track_number: 4,
        duration_ms: 252504,
        external_ids: { isrc: 'USUM71500177' },
        external_urls: {
          spotify: 'https://open.spotify.com/track/4ckVs2KqZix1xuM3ZQtNb2',
        },
        href: 'https://api.spotify.com/v1/tracks/4ckVs2KqZix1xuM3ZQtNb2',
        id: '4ckVs2KqZix1xuM3ZQtNb2',
        name: 'Beggin For Thread - BTS Remix',
        popularity: 20,
        uri: 'spotify:track:4ckVs2KqZix1xuM3ZQtNb2',
        is_local: false,
      },
      video_thumbnail: { url: null },
    },
  ],
  limit: 100,
  next: 'https://api.spotify.com/v1/playlists/7M9SBTpzYTGtnWSr1ssOJx/tracks?offset=100&limit=100&locale=en-US,en;q%3D0.5',
  offset: 0,
  previous: null,
  total: 3549,
} as any;

export const searchResp = {
  tracks: {
    href: 'https://api.spotify.com/v1/search?offset=0&limit=5&query=All%20Time%20Low&type=track&locale=en-US,en;q%3D0.5',
    limit: 5,
    next: 'https://api.spotify.com/v1/search?offset=5&limit=5&query=All%20Time%20Low&type=track&locale=en-US,en;q%3D0.5',
    offset: 0,
    previous: null,
    total: 1000,
    items: [
      {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/50JJSqHUf2RQ9xsHs0KMHg',
              },
              href: 'https://api.spotify.com/v1/artists/50JJSqHUf2RQ9xsHs0KMHg',
              id: '50JJSqHUf2RQ9xsHs0KMHg',
              name: 'Jon Bellion',
              type: 'artist',
              uri: 'spotify:artist:50JJSqHUf2RQ9xsHs0KMHg',
            },
          ],
          available_markets: ['CA', 'MX', 'US'],
          external_urls: {
            spotify: 'https://open.spotify.com/album/2jJReDZqTuAxr4R0ItimZc',
          },
          href: 'https://api.spotify.com/v1/albums/2jJReDZqTuAxr4R0ItimZc',
          id: '2jJReDZqTuAxr4R0ItimZc',
          images: [
            {
              height: 640,
              width: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273804533fa6608d1c8d420dbeb',
            },
            {
              height: 300,
              width: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02804533fa6608d1c8d420dbeb',
            },
            {
              height: 64,
              width: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851804533fa6608d1c8d420dbeb',
            },
          ],
          is_playable: true,
          name: 'The Human Condition',
          release_date: '2016-06-10',
          release_date_precision: 'day',
          total_tracks: 14,
          type: 'album',
          uri: 'spotify:album:2jJReDZqTuAxr4R0ItimZc',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/50JJSqHUf2RQ9xsHs0KMHg',
            },
            href: 'https://api.spotify.com/v1/artists/50JJSqHUf2RQ9xsHs0KMHg',
            id: '50JJSqHUf2RQ9xsHs0KMHg',
            name: 'Jon Bellion',
            type: 'artist',
            uri: 'spotify:artist:50JJSqHUf2RQ9xsHs0KMHg',
          },
        ],
        available_markets: ['CA', 'MX', 'US'],
        disc_number: 1,
        duration_ms: 217603,
        explicit: true,
        external_ids: { isrc: 'USUM71603666' },
        external_urls: {
          spotify: 'https://open.spotify.com/track/0SuLAslEMFZAXf0SwY7syi',
        },
        href: 'https://api.spotify.com/v1/tracks/0SuLAslEMFZAXf0SwY7syi',
        id: '0SuLAslEMFZAXf0SwY7syi',
        is_local: false,
        is_playable: true,
        name: 'All Time Low',
        popularity: 65,
        preview_url: null,
        track_number: 3,
        type: 'track',
        uri: 'spotify:track:0SuLAslEMFZAXf0SwY7syi',
      },
      {
        album: {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/50JJSqHUf2RQ9xsHs0KMHg',
              },
              href: 'https://api.spotify.com/v1/artists/50JJSqHUf2RQ9xsHs0KMHg',
              id: '50JJSqHUf2RQ9xsHs0KMHg',
              name: 'Jon Bellion',
              type: 'artist',
              uri: 'spotify:artist:50JJSqHUf2RQ9xsHs0KMHg',
            },
          ],
          available_markets: ['AR', 'AU', 'AT', 'BE', 'BO'],
          external_urls: {
            spotify: 'https://open.spotify.com/album/3HV9EG2SOmJX7PKvKUCst6',
          },
          href: 'https://api.spotify.com/v1/albums/3HV9EG2SOmJX7PKvKUCst6',
          id: '3HV9EG2SOmJX7PKvKUCst6',
          images: [
            {
              height: 640,
              width: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b2738519af1fdbf5ea0e702a8bd2',
            },
            {
              height: 300,
              width: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e028519af1fdbf5ea0e702a8bd2',
            },
            {
              height: 64,
              width: 64,
              url: 'https://i.scdn.co/image/ab67616d000048518519af1fdbf5ea0e702a8bd2',
            },
          ],
          is_playable: true,
          name: 'All Time Low',
          release_date: '2017-03-10',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:3HV9EG2SOmJX7PKvKUCst6',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/50JJSqHUf2RQ9xsHs0KMHg',
            },
            href: 'https://api.spotify.com/v1/artists/50JJSqHUf2RQ9xsHs0KMHg',
            id: '50JJSqHUf2RQ9xsHs0KMHg',
            name: 'Jon Bellion',
            type: 'artist',
            uri: 'spotify:artist:50JJSqHUf2RQ9xsHs0KMHg',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2SrSdSvpminqmStGELCSNd',
            },
            href: 'https://api.spotify.com/v1/artists/2SrSdSvpminqmStGELCSNd',
            id: '2SrSdSvpminqmStGELCSNd',
            name: 'Stormzy',
            type: 'artist',
            uri: 'spotify:artist:2SrSdSvpminqmStGELCSNd',
          },
        ],
        available_markets: ['AR', 'AU', 'AT', 'BE'],
        disc_number: 1,
        duration_ms: 219460,
        explicit: true,
        external_ids: { isrc: 'USUM71701923' },
        external_urls: {
          spotify: 'https://open.spotify.com/track/7qVjoGvjdOFfk3uKVhvZU9',
        },
        href: 'https://api.spotify.com/v1/tracks/7qVjoGvjdOFfk3uKVhvZU9',
        id: '7qVjoGvjdOFfk3uKVhvZU9',
        is_local: false,
        is_playable: true,
        name: 'All Time Low',
        popularity: 48,
        preview_url: null,
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:7qVjoGvjdOFfk3uKVhvZU9',
      },
      {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/46gyXjRIvN1NL1eCB8GBxo',
              },
              href: 'https://api.spotify.com/v1/artists/46gyXjRIvN1NL1eCB8GBxo',
              id: '46gyXjRIvN1NL1eCB8GBxo',
              name: 'All Time Low',
              type: 'artist',
              uri: 'spotify:artist:46gyXjRIvN1NL1eCB8GBxo',
            },
          ],
          available_markets: ['AR', 'AU', 'AT', 'BE'],
          external_urls: {
            spotify: 'https://open.spotify.com/album/0H4ELcHequ3OligrjWfrZP',
          },
          href: 'https://api.spotify.com/v1/albums/0H4ELcHequ3OligrjWfrZP',
          id: '0H4ELcHequ3OligrjWfrZP',
          images: [
            {
              height: 640,
              width: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273c8913cd7b91bb7f6bbbec305',
            },
            {
              height: 300,
              width: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02c8913cd7b91bb7f6bbbec305',
            },
            {
              height: 64,
              width: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851c8913cd7b91bb7f6bbbec305',
            },
          ],
          is_playable: true,
          name: "So Wrong, It's Right",
          release_date: '2007-09-25',
          release_date_precision: 'day',
          total_tracks: 12,
          type: 'album',
          uri: 'spotify:album:0H4ELcHequ3OligrjWfrZP',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/46gyXjRIvN1NL1eCB8GBxo',
            },
            href: 'https://api.spotify.com/v1/artists/46gyXjRIvN1NL1eCB8GBxo',
            id: '46gyXjRIvN1NL1eCB8GBxo',
            name: 'All Time Low',
            type: 'artist',
            uri: 'spotify:artist:46gyXjRIvN1NL1eCB8GBxo',
          },
        ],
        available_markets: ['AR', 'AU', 'AT', 'BE'],
        disc_number: 1,
        duration_ms: 182826,
        explicit: false,
        external_ids: { isrc: 'USHR20747017' },
        external_urls: {
          spotify: 'https://open.spotify.com/track/0JJP0IS4w0fJx01EcrfkDe',
        },
        href: 'https://api.spotify.com/v1/tracks/0JJP0IS4w0fJx01EcrfkDe',
        id: '0JJP0IS4w0fJx01EcrfkDe',
        is_local: false,
        is_playable: true,
        name: 'Dear Maria, Count Me In',
        popularity: 75,
        preview_url: null,
        track_number: 6,
        type: 'track',
        uri: 'spotify:track:0JJP0IS4w0fJx01EcrfkDe',
      },
      {
        album: {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/46gyXjRIvN1NL1eCB8GBxo',
              },
              href: 'https://api.spotify.com/v1/artists/46gyXjRIvN1NL1eCB8GBxo',
              id: '46gyXjRIvN1NL1eCB8GBxo',
              name: 'All Time Low',
              type: 'artist',
              uri: 'spotify:artist:46gyXjRIvN1NL1eCB8GBxo',
            },
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/3Uobr6LgQpBbk6k4QGAb3V',
              },
              href: 'https://api.spotify.com/v1/artists/3Uobr6LgQpBbk6k4QGAb3V',
              id: '3Uobr6LgQpBbk6k4QGAb3V',
              name: 'I Prevail',
              type: 'artist',
              uri: 'spotify:artist:3Uobr6LgQpBbk6k4QGAb3V',
            },
          ],
          available_markets: ['AR', 'AU', 'AT', 'BE', 'BO'],
          external_urls: {
            spotify: 'https://open.spotify.com/album/2aq4k4OA1jfupRu9eWYRMA',
          },
          href: 'https://api.spotify.com/v1/albums/2aq4k4OA1jfupRu9eWYRMA',
          id: '2aq4k4OA1jfupRu9eWYRMA',
          images: [
            {
              height: 640,
              width: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b27337babbaa644b7e93f261f1bb',
            },
            {
              height: 300,
              width: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e0237babbaa644b7e93f261f1bb',
            },
            {
              height: 64,
              width: 64,
              url: 'https://i.scdn.co/image/ab67616d0000485137babbaa644b7e93f261f1bb',
            },
          ],
          is_playable: true,
          name: 'Hate This Song',
          release_date: '2024-09-17',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:2aq4k4OA1jfupRu9eWYRMA',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/46gyXjRIvN1NL1eCB8GBxo',
            },
            href: 'https://api.spotify.com/v1/artists/46gyXjRIvN1NL1eCB8GBxo',
            id: '46gyXjRIvN1NL1eCB8GBxo',
            name: 'All Time Low',
            type: 'artist',
            uri: 'spotify:artist:46gyXjRIvN1NL1eCB8GBxo',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3Uobr6LgQpBbk6k4QGAb3V',
            },
            href: 'https://api.spotify.com/v1/artists/3Uobr6LgQpBbk6k4QGAb3V',
            id: '3Uobr6LgQpBbk6k4QGAb3V',
            name: 'I Prevail',
            type: 'artist',
            uri: 'spotify:artist:3Uobr6LgQpBbk6k4QGAb3V',
          },
        ],
        available_markets: ['AR', 'AU', 'AT', 'BE', 'BO'],
        disc_number: 1,
        duration_ms: 175693,
        explicit: true,
        external_ids: { isrc: 'US5262426747' },
        external_urls: {
          spotify: 'https://open.spotify.com/track/3keius8Oa84Xwul5LdvO1c',
        },
        href: 'https://api.spotify.com/v1/tracks/3keius8Oa84Xwul5LdvO1c',
        id: '3keius8Oa84Xwul5LdvO1c',
        is_local: false,
        is_playable: true,
        name: 'Hate This Song',
        popularity: 60,
        preview_url: null,
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:3keius8Oa84Xwul5LdvO1c',
      },
      {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/4E2rKHVDssGJm2SCDOMMJB',
              },
              href: 'https://api.spotify.com/v1/artists/4E2rKHVDssGJm2SCDOMMJB',
              id: '4E2rKHVDssGJm2SCDOMMJB',
              name: 'Doechii',
              type: 'artist',
              uri: 'spotify:artist:4E2rKHVDssGJm2SCDOMMJB',
            },
          ],
          available_markets: ['AR', 'AU', 'AT', 'BE'],
          external_urls: {
            spotify: 'https://open.spotify.com/album/60UzB8mOCMpc7xkuJE6Bwc',
          },
          href: 'https://api.spotify.com/v1/albums/60UzB8mOCMpc7xkuJE6Bwc',
          id: '60UzB8mOCMpc7xkuJE6Bwc',
          images: [
            {
              height: 640,
              width: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273b245099fe26319344ddf6054',
            },
            {
              height: 300,
              width: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02b245099fe26319344ddf6054',
            },
            {
              height: 64,
              width: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851b245099fe26319344ddf6054',
            },
          ],
          is_playable: true,
          name: 'Alligator Bites Never Heal',
          release_date: '2024-08-30',
          release_date_precision: 'day',
          total_tracks: 19,
          type: 'album',
          uri: 'spotify:album:60UzB8mOCMpc7xkuJE6Bwc',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/4E2rKHVDssGJm2SCDOMMJB',
            },
            href: 'https://api.spotify.com/v1/artists/4E2rKHVDssGJm2SCDOMMJB',
            id: '4E2rKHVDssGJm2SCDOMMJB',
            name: 'Doechii',
            type: 'artist',
            uri: 'spotify:artist:4E2rKHVDssGJm2SCDOMMJB',
          },
        ],
        available_markets: ['AR', 'AU', 'AT', 'BE'],
        disc_number: 1,
        duration_ms: 159586,
        explicit: true,
        external_ids: { isrc: 'USUG12405664' },
        external_urls: {
          spotify: 'https://open.spotify.com/track/1eTaznNW4Xxtx9za2SMTXB',
        },
        href: 'https://api.spotify.com/v1/tracks/1eTaznNW4Xxtx9za2SMTXB',
        id: '1eTaznNW4Xxtx9za2SMTXB',
        is_local: false,
        is_playable: true,
        name: 'DENIAL IS A RIVER',
        popularity: 87,
        preview_url: null,
        track_number: 4,
        type: 'track',
        uri: 'spotify:track:1eTaznNW4Xxtx9za2SMTXB',
      },
    ],
  },
};

export const likedSongs: SpotifyApi.UsersSavedTracksResponse = {
  href: 'https://api.spotify.com/v1/me/shows?offset=0&limit=20',
  limit: 20,
  next: 'https://api.spotify.com/v1/me/shows?offset=1&limit=1',
  offset: 0,
  previous: 'https://api.spotify.com/v1/me/shows?offset=1&limit=1',
  total: 5,
  items: [
    {
      added_at: '2024-03-01T12:00:00Z',
      track: {
        album: {
          album_type: 'album',
          available_markets: ['US', 'CA', 'GB'],
          external_urls: {
            spotify: 'https://open.spotify.com/album/6kZDoBvgecsnwc7PvnO6iG',
          },
          href: 'https://api.spotify.com/v1/albums/6kZDoBvgecsnwc7PvnO6iG',
          id: '6kZDoBvgecsnwc7PvnO6iG',
          images: [
            {
              url: 'https://i.scdn.co/image/ab67616d00001e02bb2d30678d2e999ebcfdf28c',
              height: 300,
              width: 300,
            },
          ],
          name: 'Midnights',
          type: 'album',
          uri: 'spotify:album:6kZDoBvgecsnwc7PvnO6iG',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/06HL4zM2S2ZpXmC4L3pI3p',
            },
            href: 'https://api.spotify.com/v1/artists/06HL4zM2S2ZpXmC4L3pI3p',
            id: '06HL4zM2S2ZpXmC4L3pI3p',
            name: 'Taylor Swift',
            type: 'artist',
            uri: 'spotify:artist:06HL4zM2S2ZpXmC4L3pI3p',
          },
        ],
        available_markets: ['US', 'CA', 'GB'],
        disc_number: 1,
        duration_ms: 200690,
        explicit: false,
        external_ids: {
          isrc: 'USCJY2231003',
          ean: 'string',
          upc: 'string',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/0V3wPSX9ygBnCm8psDIegu',
        },
        href: 'https://api.spotify.com/v1/tracks/0V3wPSX9ygBnCm8psDIegu',
        id: '0V3wPSX9ygBnCm8psDIegu',
        is_playable: true,
        name: 'Anti-Hero',
        popularity: 92,
        preview_url: 'https://p.scdn.co/mp3-preview/12345',
        track_number: 3,
        type: 'track',
        uri: 'spotify:track:0V3wPSX9ygBnCm8psDIegu',
      },
    },
    {
      added_at: '2024-03-02T14:30:00Z',
      track: {
        album: {
          album_type: 'album',
          available_markets: ['US', 'CA'],
          external_urls: {
            spotify: 'https://open.spotify.com/album/5P9V80z9T6vU7e7qX6S5r6',
          },
          href: 'https://api.spotify.com/v1/albums/5P9V80z9T6vU7e7qX6S5r6',
          id: '5P9V80z9T6vU7e7qX6S5r6',
          images: [
            {
              url: 'https://i.scdn.co/image/ab67616d00001e02e811a7687d0c614ef44f51cd',
              height: 300,
              width: 300,
            },
          ],
          name: 'Justice',
          type: 'album',
          uri: 'spotify:album:5P9V80z9T6vU7e7qX6S5r6',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1uNFoWOzWveC4fCIjSTnRq',
            },
            href: 'https://api.spotify.com/v1/artists/1uNFoWOzWveC4fCIjSTnRq',
            id: '1uNFoWOzWveC4fCIjSTnRq',
            name: 'Justin Bieber',
            type: 'artist',
            uri: 'spotify:artist:1uNFoWOzWveC4fCIjSTnRq',
          },
        ],
        available_markets: ['US', 'CA'],
        disc_number: 1,
        duration_ms: 198081,
        explicit: true,
        external_ids: {
          isrc: 'USUM72105936',
          ean: 'string',
          upc: 'string',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/4iJyoBOLtHqaGxP12qzhQI',
        },
        href: 'https://api.spotify.com/v1/tracks/4iJyoBOLtHqaGxP12qzhQI',
        id: '4iJyoBOLtHqaGxP12qzhQI',
        is_playable: true,
        name: 'Peaches',
        popularity: 88,
        preview_url: 'https://p.scdn.co/mp3-preview/67890',
        track_number: 12,
        type: 'track',
        uri: 'spotify:track:4iJyoBOLtHqaGxP12qzhQI',
      },
    },
    {
      added_at: '2024-03-03T09:15:00Z',
      track: {
        album: {
          album_type: 'album',
          available_markets: ['US', 'CA', 'IT'],
          external_urls: {
            spotify: 'https://open.spotify.com/album/4m2880jivVYhC1q9Cg9Jp6',
          },
          href: 'https://api.spotify.com/v1/albums/4m2880jivVYhC1q9Cg9Jp6',
          id: '4m2880jivVYhC1q9Cg9Jp6',
          images: [
            {
              url: 'https://i.scdn.co/image/ab67616d00001e02f068832677610e3047b19641',
              height: 300,
              width: 300,
            },
          ],
          name: 'The Fame Monster',
          type: 'album',
          uri: 'spotify:album:4m2880jivVYhC1q9Cg9Jp6',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1HY2JtFsYpDwwv61ccq7Xz',
            },
            href: 'https://api.spotify.com/v1/artists/1HY2JtFsYpDwwv61ccq7Xz',
            id: '1HY2JtFsYpDwwv61ccq7Xz',
            name: 'Lady Gaga',
            type: 'artist',
            uri: 'spotify:artist:1HY2JtFsYpDwwv61ccq7Xz',
          },
        ],
        available_markets: ['US', 'CA', 'IT'],
        disc_number: 1,
        duration_ms: 294000,
        explicit: false,
        external_ids: {
          isrc: 'USUM70982548',
          ean: 'string',
          upc: 'string',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/0SiyN4glFeYWo2Zunp596C',
        },
        href: 'https://api.spotify.com/v1/tracks/0SiyN4glFeYWo2Zunp596C',
        id: '0SiyN4glFeYWo2Zunp596C',
        is_playable: true,
        name: 'Bad Romance',
        popularity: 85,
        preview_url: 'https://p.scdn.co/mp3-preview/13579',
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:0SiyN4glFeYWo2Zunp596C',
      },
    },
    {
      added_at: '2024-03-04T18:45:00Z',
      track: {
        album: {
          album_type: 'album',
          available_markets: ['US', 'CA'],
          external_urls: {
            spotify: 'https://open.spotify.com/album/097775676b664746467657',
          },
          href: 'https://api.spotify.com/v1/albums/097775676b664746467657',
          id: '097775676b664746467657',
          images: [
            {
              url: 'https://i.scdn.co/image/ab67616d00001e0274296766763476476567',
              height: 300,
              width: 300,
            },
          ],
          name: 'Dark Sky Paradise',
          type: 'album',
          uri: 'spotify:album:097775676b664746467657',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0Y5tJX1_Big_Sean_ID',
            },
            href: 'https://api.spotify.com/v1/artists/0Y5tJX1_Big_Sean_ID',
            id: '0Y5tJX1_Big_Sean_ID',
            name: 'Big Sean',
            type: 'artist',
            uri: 'spotify:artist:0Y5tJX1_Big_Sean_ID',
          },
        ],
        available_markets: ['US', 'CA'],
        disc_number: 1,
        duration_ms: 284000,
        explicit: true,
        external_ids: {
          isrc: 'USUM71416073',
          ean: 'string',
          upc: 'string',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/764536251436',
        },
        href: 'https://api.spotify.com/v1/tracks/764536251436',
        id: '764536251436',
        is_playable: true,
        name: "I Don't F*** With You",
        popularity: 80,
        preview_url: 'https://p.scdn.co/mp3-preview/24680',
        track_number: 2,
        type: 'track',
        uri: 'spotify:track:764536251436',
      },
    },
    {
      added_at: '2024-03-05T20:10:00Z',
      track: {
        album: {
          album_type: 'album',
          available_markets: ['US', 'CA', 'GB'],
          external_urls: {
            spotify: 'https://open.spotify.com/album/4jox37IRfwRZZZ78vYnH7T',
          },
          href: 'https://api.spotify.com/v1/albums/4jox37IRfwRZZZ78vYnH7T',
          id: '4jox37IRfwRZZZ78vYnH7T',
          images: [
            {
              url: 'https://i.scdn.co/image/ab67616d00001e0288edc795664701759c2445d9',
              height: 300,
              width: 300,
            },
          ],
          name: 'After Hours',
          type: 'album',
          uri: 'spotify:album:4jox37IRfwRZZZ78vYnH7T',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1Xyo4u3uXC1ZmMpatF0t4g',
            },
            href: 'https://api.spotify.com/v1/artists/1Xyo4u3uXC1ZmMpatF0t4g',
            id: '1Xyo4u3uXC1ZmMpatF0t4g',
            name: 'The Weeknd',
            type: 'artist',
            uri: 'spotify:artist:1Xyo4u3uXC1ZmMpatF0t4g',
          },
        ],
        available_markets: ['US', 'CA', 'GB'],
        disc_number: 1,
        duration_ms: 200040,
        explicit: false,
        external_ids: {
          isrc: 'USUM71922435',
          ean: 'string',
          upc: 'string',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b',
        },
        href: 'https://api.spotify.com/v1/tracks/0VjIjW4GlUZAMYd2vXMi3b',
        id: '0VjIjW4GlUZAMYd2vXMi3b',
        is_playable: true,
        name: 'Blinding Lights',
        popularity: 96,
        preview_url: 'https://p.scdn.co/mp3-preview/11223',
        track_number: 9,
        type: 'track',
        uri: 'spotify:track:0VjIjW4GlUZAMYd2vXMi3b',
      },
    },
  ],
};
